packages:
  github.com/notes/zesh:
    config:
      all: true
      recursive: true
      inpackage: true
      dir: '{{.InterfaceDir}}'
      filename: mock_{{.InterfaceName}}.go
      mockname: Mock{{.InterfaceName}}
