// Code generated by mockery v2.53.5. DO NOT EDIT.

package cache

import (
	model "github.com/OneNoted/zeshion/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with no fields
func (_m *MockCache) Read() (CachedData, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 CachedData
	var r1 error
	if rf, ok := ret.Get(0).(func() (CachedData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() CachedData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(CachedData)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockCache_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockCache_Expecter) Read() *MockCache_Read_Call {
	return &MockCache_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockCache_Read_Call) Run(run func()) *MockCache_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Read_Call) Return(_a0 CachedData, _a1 error) *MockCache_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Read_Call) RunAndReturn(run func() (CachedData, error)) *MockCache_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: sessions
func (_m *MockCache) Write(sessions model.SeshSessions) error {
	ret := _m.Called(sessions)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SeshSessions) error); ok {
		r0 = rf(sessions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockCache_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - sessions model.SeshSessions
func (_e *MockCache_Expecter) Write(sessions interface{}) *MockCache_Write_Call {
	return &MockCache_Write_Call{Call: _e.mock.On("Write", sessions)}
}

func (_c *MockCache_Write_Call) Run(run func(sessions model.SeshSessions)) *MockCache_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.SeshSessions))
	})
	return _c
}

func (_c *MockCache_Write_Call) Return(_a0 error) *MockCache_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_Write_Call) RunAndReturn(run func(model.SeshSessions) error) *MockCache_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
