// Code generated by mockery v2.53.5. DO NOT EDIT.

package picker

import mock "github.com/stretchr/testify/mock"

// MockPicker is an autogenerated mock type for the Picker type
type MockPicker struct {
	mock.Mock
}

type MockPicker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPicker) EXPECT() *MockPicker_Expecter {
	return &MockPicker_Expecter{mock: &_m.Mock}
}

// Pick provides a mock function with given fields: fetchFunc, opts
func (_m *MockPicker) Pick(fetchFunc FetchFunc, opts PickerOptions) (string, error) {
	ret := _m.Called(fetchFunc, opts)

	if len(ret) == 0 {
		panic("no return value specified for Pick")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(FetchFunc, PickerOptions) (string, error)); ok {
		return rf(fetchFunc, opts)
	}
	if rf, ok := ret.Get(0).(func(FetchFunc, PickerOptions) string); ok {
		r0 = rf(fetchFunc, opts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(FetchFunc, PickerOptions) error); ok {
		r1 = rf(fetchFunc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPicker_Pick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pick'
type MockPicker_Pick_Call struct {
	*mock.Call
}

// Pick is a helper method to define mock.On call
//   - fetchFunc FetchFunc
//   - opts PickerOptions
func (_e *MockPicker_Expecter) Pick(fetchFunc interface{}, opts interface{}) *MockPicker_Pick_Call {
	return &MockPicker_Pick_Call{Call: _e.mock.On("Pick", fetchFunc, opts)}
}

func (_c *MockPicker_Pick_Call) Run(run func(fetchFunc FetchFunc, opts PickerOptions)) *MockPicker_Pick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(FetchFunc), args[1].(PickerOptions))
	})
	return _c
}

func (_c *MockPicker_Pick_Call) Return(_a0 string, _a1 error) *MockPicker_Pick_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPicker_Pick_Call) RunAndReturn(run func(FetchFunc, PickerOptions) (string, error)) *MockPicker_Pick_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPicker creates a new instance of MockPicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPicker {
	mock := &MockPicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
