// Code generated by mockery v2.53.5. DO NOT EDIT.

package picker

import (
	model "github.com/notes/zesh/model"
	mock "github.com/stretchr/testify/mock"
)

// MockFetchFunc is an autogenerated mock type for the FetchFunc type
type MockFetchFunc struct {
	mock.Mock
}

type MockFetchFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetchFunc) EXPECT() *MockFetchFunc_Expecter {
	return &MockFetchFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockFetchFunc) Execute() (model.SeshSessions, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 model.SeshSessions
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.SeshSessions, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.SeshSessions); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.SeshSessions)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetchFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFetchFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockFetchFunc_Expecter) Execute() *MockFetchFunc_Execute_Call {
	return &MockFetchFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockFetchFunc_Execute_Call) Run(run func()) *MockFetchFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFetchFunc_Execute_Call) Return(_a0 model.SeshSessions, _a1 error) *MockFetchFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetchFunc_Execute_Call) RunAndReturn(run func() (model.SeshSessions, error)) *MockFetchFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFetchFunc creates a new instance of MockFetchFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetchFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetchFunc {
	mock := &MockFetchFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
