// Code generated by mockery v2.53.5. DO NOT EDIT.

package tmux

import (
	model "github.com/notes/zeshion/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTmux is an autogenerated mock type for the Tmux type
type MockTmux struct {
	mock.Mock
}

type MockTmux_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTmux) EXPECT() *MockTmux_Expecter {
	return &MockTmux_Expecter{mock: &_m.Mock}
}

// AttachSession provides a mock function with given fields: targetSession
func (_m *MockTmux) AttachSession(targetSession string) (string, error) {
	ret := _m.Called(targetSession)

	if len(ret) == 0 {
		panic("no return value specified for AttachSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(targetSession)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(targetSession)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(targetSession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_AttachSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachSession'
type MockTmux_AttachSession_Call struct {
	*mock.Call
}

// AttachSession is a helper method to define mock.On call
//   - targetSession string
func (_e *MockTmux_Expecter) AttachSession(targetSession interface{}) *MockTmux_AttachSession_Call {
	return &MockTmux_AttachSession_Call{Call: _e.mock.On("AttachSession", targetSession)}
}

func (_c *MockTmux_AttachSession_Call) Run(run func(targetSession string)) *MockTmux_AttachSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTmux_AttachSession_Call) Return(_a0 string, _a1 error) *MockTmux_AttachSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_AttachSession_Call) RunAndReturn(run func(string) (string, error)) *MockTmux_AttachSession_Call {
	_c.Call.Return(run)
	return _c
}

// CapturePane provides a mock function with given fields: targetSession
func (_m *MockTmux) CapturePane(targetSession string) (string, error) {
	ret := _m.Called(targetSession)

	if len(ret) == 0 {
		panic("no return value specified for CapturePane")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(targetSession)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(targetSession)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(targetSession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_CapturePane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePane'
type MockTmux_CapturePane_Call struct {
	*mock.Call
}

// CapturePane is a helper method to define mock.On call
//   - targetSession string
func (_e *MockTmux_Expecter) CapturePane(targetSession interface{}) *MockTmux_CapturePane_Call {
	return &MockTmux_CapturePane_Call{Call: _e.mock.On("CapturePane", targetSession)}
}

func (_c *MockTmux_CapturePane_Call) Run(run func(targetSession string)) *MockTmux_CapturePane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTmux_CapturePane_Call) Return(_a0 string, _a1 error) *MockTmux_CapturePane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_CapturePane_Call) RunAndReturn(run func(string) (string, error)) *MockTmux_CapturePane_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentSession provides a mock function with no fields
func (_m *MockTmux) GetCurrentSession() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_GetCurrentSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentSession'
type MockTmux_GetCurrentSession_Call struct {
	*mock.Call
}

// GetCurrentSession is a helper method to define mock.On call
func (_e *MockTmux_Expecter) GetCurrentSession() *MockTmux_GetCurrentSession_Call {
	return &MockTmux_GetCurrentSession_Call{Call: _e.mock.On("GetCurrentSession")}
}

func (_c *MockTmux_GetCurrentSession_Call) Run(run func()) *MockTmux_GetCurrentSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmux_GetCurrentSession_Call) Return(_a0 string, _a1 error) *MockTmux_GetCurrentSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_GetCurrentSession_Call) RunAndReturn(run func() (string, error)) *MockTmux_GetCurrentSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsAttached provides a mock function with no fields
func (_m *MockTmux) IsAttached() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAttached")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTmux_IsAttached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAttached'
type MockTmux_IsAttached_Call struct {
	*mock.Call
}

// IsAttached is a helper method to define mock.On call
func (_e *MockTmux_Expecter) IsAttached() *MockTmux_IsAttached_Call {
	return &MockTmux_IsAttached_Call{Call: _e.mock.On("IsAttached")}
}

func (_c *MockTmux_IsAttached_Call) Run(run func()) *MockTmux_IsAttached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmux_IsAttached_Call) Return(_a0 bool) *MockTmux_IsAttached_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTmux_IsAttached_Call) RunAndReturn(run func() bool) *MockTmux_IsAttached_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function with no fields
func (_m *MockTmux) ListSessions() ([]*model.TmuxSession, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 []*model.TmuxSession
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.TmuxSession, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.TmuxSession); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TmuxSession)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type MockTmux_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
func (_e *MockTmux_Expecter) ListSessions() *MockTmux_ListSessions_Call {
	return &MockTmux_ListSessions_Call{Call: _e.mock.On("ListSessions")}
}

func (_c *MockTmux_ListSessions_Call) Run(run func()) *MockTmux_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmux_ListSessions_Call) Return(_a0 []*model.TmuxSession, _a1 error) *MockTmux_ListSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_ListSessions_Call) RunAndReturn(run func() ([]*model.TmuxSession, error)) *MockTmux_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTmuxPanes provides a mock function with no fields
func (_m *MockTmux) ListTmuxPanes() ([]*model.TmuxPane, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTmuxPanes")
	}

	var r0 []*model.TmuxPane
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.TmuxPane, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.TmuxPane); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TmuxPane)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_ListTmuxPanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTmuxPanes'
type MockTmux_ListTmuxPanes_Call struct {
	*mock.Call
}

// ListTmuxPanes is a helper method to define mock.On call
func (_e *MockTmux_Expecter) ListTmuxPanes() *MockTmux_ListTmuxPanes_Call {
	return &MockTmux_ListTmuxPanes_Call{Call: _e.mock.On("ListTmuxPanes")}
}

func (_c *MockTmux_ListTmuxPanes_Call) Run(run func()) *MockTmux_ListTmuxPanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmux_ListTmuxPanes_Call) Return(_a0 []*model.TmuxPane, _a1 error) *MockTmux_ListTmuxPanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_ListTmuxPanes_Call) RunAndReturn(run func() ([]*model.TmuxPane, error)) *MockTmux_ListTmuxPanes_Call {
	_c.Call.Return(run)
	return _c
}

// ListWindows provides a mock function with given fields: targetSession
func (_m *MockTmux) ListWindows(targetSession string) ([]*model.TmuxWindow, error) {
	ret := _m.Called(targetSession)

	if len(ret) == 0 {
		panic("no return value specified for ListWindows")
	}

	var r0 []*model.TmuxWindow
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.TmuxWindow, error)); ok {
		return rf(targetSession)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.TmuxWindow); ok {
		r0 = rf(targetSession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TmuxWindow)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(targetSession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_ListWindows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWindows'
type MockTmux_ListWindows_Call struct {
	*mock.Call
}

// ListWindows is a helper method to define mock.On call
//   - targetSession string
func (_e *MockTmux_Expecter) ListWindows(targetSession interface{}) *MockTmux_ListWindows_Call {
	return &MockTmux_ListWindows_Call{Call: _e.mock.On("ListWindows", targetSession)}
}

func (_c *MockTmux_ListWindows_Call) Run(run func(targetSession string)) *MockTmux_ListWindows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTmux_ListWindows_Call) Return(_a0 []*model.TmuxWindow, _a1 error) *MockTmux_ListWindows_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_ListWindows_Call) RunAndReturn(run func(string) ([]*model.TmuxWindow, error)) *MockTmux_ListWindows_Call {
	_c.Call.Return(run)
	return _c
}

// NewSession provides a mock function with given fields: sessionName, startDir, shellCommand
func (_m *MockTmux) NewSession(sessionName string, startDir string, shellCommand string) (string, error) {
	ret := _m.Called(sessionName, startDir, shellCommand)

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(sessionName, startDir, shellCommand)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(sessionName, startDir, shellCommand)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(sessionName, startDir, shellCommand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_NewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSession'
type MockTmux_NewSession_Call struct {
	*mock.Call
}

// NewSession is a helper method to define mock.On call
//   - sessionName string
//   - startDir string
//   - shellCommand string
func (_e *MockTmux_Expecter) NewSession(sessionName interface{}, startDir interface{}, shellCommand interface{}) *MockTmux_NewSession_Call {
	return &MockTmux_NewSession_Call{Call: _e.mock.On("NewSession", sessionName, startDir, shellCommand)}
}

func (_c *MockTmux_NewSession_Call) Run(run func(sessionName string, startDir string, shellCommand string)) *MockTmux_NewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTmux_NewSession_Call) Return(_a0 string, _a1 error) *MockTmux_NewSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_NewSession_Call) RunAndReturn(run func(string, string, string) (string, error)) *MockTmux_NewSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewWindow provides a mock function with given fields: startDir, name, shellCommand
func (_m *MockTmux) NewWindow(startDir string, name string, shellCommand string) (string, error) {
	ret := _m.Called(startDir, name, shellCommand)

	if len(ret) == 0 {
		panic("no return value specified for NewWindow")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(startDir, name, shellCommand)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(startDir, name, shellCommand)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(startDir, name, shellCommand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_NewWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWindow'
type MockTmux_NewWindow_Call struct {
	*mock.Call
}

// NewWindow is a helper method to define mock.On call
//   - startDir string
//   - name string
//   - shellCommand string
func (_e *MockTmux_Expecter) NewWindow(startDir interface{}, name interface{}, shellCommand interface{}) *MockTmux_NewWindow_Call {
	return &MockTmux_NewWindow_Call{Call: _e.mock.On("NewWindow", startDir, name, shellCommand)}
}

func (_c *MockTmux_NewWindow_Call) Run(run func(startDir string, name string, shellCommand string)) *MockTmux_NewWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTmux_NewWindow_Call) Return(_a0 string, _a1 error) *MockTmux_NewWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_NewWindow_Call) RunAndReturn(run func(string, string, string) (string, error)) *MockTmux_NewWindow_Call {
	_c.Call.Return(run)
	return _c
}

// NewWindowInSession provides a mock function with given fields: name, startDir, targetSession, shellCommand
func (_m *MockTmux) NewWindowInSession(name string, startDir string, targetSession string, shellCommand string) (string, error) {
	ret := _m.Called(name, startDir, targetSession, shellCommand)

	if len(ret) == 0 {
		panic("no return value specified for NewWindowInSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, error)); ok {
		return rf(name, startDir, targetSession, shellCommand)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(name, startDir, targetSession, shellCommand)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(name, startDir, targetSession, shellCommand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_NewWindowInSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWindowInSession'
type MockTmux_NewWindowInSession_Call struct {
	*mock.Call
}

// NewWindowInSession is a helper method to define mock.On call
//   - name string
//   - startDir string
//   - targetSession string
//   - shellCommand string
func (_e *MockTmux_Expecter) NewWindowInSession(name interface{}, startDir interface{}, targetSession interface{}, shellCommand interface{}) *MockTmux_NewWindowInSession_Call {
	return &MockTmux_NewWindowInSession_Call{Call: _e.mock.On("NewWindowInSession", name, startDir, targetSession, shellCommand)}
}

func (_c *MockTmux_NewWindowInSession_Call) Run(run func(name string, startDir string, targetSession string, shellCommand string)) *MockTmux_NewWindowInSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTmux_NewWindowInSession_Call) Return(_a0 string, _a1 error) *MockTmux_NewWindowInSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_NewWindowInSession_Call) RunAndReturn(run func(string, string, string, string) (string, error)) *MockTmux_NewWindowInSession_Call {
	_c.Call.Return(run)
	return _c
}

// NextWindow provides a mock function with no fields
func (_m *MockTmux) NextWindow() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextWindow")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_NextWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextWindow'
type MockTmux_NextWindow_Call struct {
	*mock.Call
}

// NextWindow is a helper method to define mock.On call
func (_e *MockTmux_Expecter) NextWindow() *MockTmux_NextWindow_Call {
	return &MockTmux_NextWindow_Call{Call: _e.mock.On("NextWindow")}
}

func (_c *MockTmux_NextWindow_Call) Run(run func()) *MockTmux_NextWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTmux_NextWindow_Call) Return(_a0 string, _a1 error) *MockTmux_NextWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_NextWindow_Call) RunAndReturn(run func() (string, error)) *MockTmux_NextWindow_Call {
	_c.Call.Return(run)
	return _c
}

// SelectPane provides a mock function with given fields: windowIndex, paneIndex
func (_m *MockTmux) SelectPane(windowIndex int, paneIndex int) (string, error) {
	ret := _m.Called(windowIndex, paneIndex)

	if len(ret) == 0 {
		panic("no return value specified for SelectPane")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (string, error)); ok {
		return rf(windowIndex, paneIndex)
	}
	if rf, ok := ret.Get(0).(func(int, int) string); ok {
		r0 = rf(windowIndex, paneIndex)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(windowIndex, paneIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_SelectPane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectPane'
type MockTmux_SelectPane_Call struct {
	*mock.Call
}

// SelectPane is a helper method to define mock.On call
//   - windowIndex int
//   - paneIndex int
func (_e *MockTmux_Expecter) SelectPane(windowIndex interface{}, paneIndex interface{}) *MockTmux_SelectPane_Call {
	return &MockTmux_SelectPane_Call{Call: _e.mock.On("SelectPane", windowIndex, paneIndex)}
}

func (_c *MockTmux_SelectPane_Call) Run(run func(windowIndex int, paneIndex int)) *MockTmux_SelectPane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTmux_SelectPane_Call) Return(_a0 string, _a1 error) *MockTmux_SelectPane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_SelectPane_Call) RunAndReturn(run func(int, int) (string, error)) *MockTmux_SelectPane_Call {
	_c.Call.Return(run)
	return _c
}

// SelectWindow provides a mock function with given fields: targetWindow
func (_m *MockTmux) SelectWindow(targetWindow string) (string, error) {
	ret := _m.Called(targetWindow)

	if len(ret) == 0 {
		panic("no return value specified for SelectWindow")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(targetWindow)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(targetWindow)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(targetWindow)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_SelectWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectWindow'
type MockTmux_SelectWindow_Call struct {
	*mock.Call
}

// SelectWindow is a helper method to define mock.On call
//   - targetWindow string
func (_e *MockTmux_Expecter) SelectWindow(targetWindow interface{}) *MockTmux_SelectWindow_Call {
	return &MockTmux_SelectWindow_Call{Call: _e.mock.On("SelectWindow", targetWindow)}
}

func (_c *MockTmux_SelectWindow_Call) Run(run func(targetWindow string)) *MockTmux_SelectWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTmux_SelectWindow_Call) Return(_a0 string, _a1 error) *MockTmux_SelectWindow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_SelectWindow_Call) RunAndReturn(run func(string) (string, error)) *MockTmux_SelectWindow_Call {
	_c.Call.Return(run)
	return _c
}

// SendKeys provides a mock function with given fields: name, command
func (_m *MockTmux) SendKeys(name string, command string) (string, error) {
	ret := _m.Called(name, command)

	if len(ret) == 0 {
		panic("no return value specified for SendKeys")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(name, command)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, command)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_SendKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendKeys'
type MockTmux_SendKeys_Call struct {
	*mock.Call
}

// SendKeys is a helper method to define mock.On call
//   - name string
//   - command string
func (_e *MockTmux_Expecter) SendKeys(name interface{}, command interface{}) *MockTmux_SendKeys_Call {
	return &MockTmux_SendKeys_Call{Call: _e.mock.On("SendKeys", name, command)}
}

func (_c *MockTmux_SendKeys_Call) Run(run func(name string, command string)) *MockTmux_SendKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTmux_SendKeys_Call) Return(_a0 string, _a1 error) *MockTmux_SendKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_SendKeys_Call) RunAndReturn(run func(string, string) (string, error)) *MockTmux_SendKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchClient provides a mock function with given fields: targetSession
func (_m *MockTmux) SwitchClient(targetSession string) (string, error) {
	ret := _m.Called(targetSession)

	if len(ret) == 0 {
		panic("no return value specified for SwitchClient")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(targetSession)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(targetSession)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(targetSession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_SwitchClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchClient'
type MockTmux_SwitchClient_Call struct {
	*mock.Call
}

// SwitchClient is a helper method to define mock.On call
//   - targetSession string
func (_e *MockTmux_Expecter) SwitchClient(targetSession interface{}) *MockTmux_SwitchClient_Call {
	return &MockTmux_SwitchClient_Call{Call: _e.mock.On("SwitchClient", targetSession)}
}

func (_c *MockTmux_SwitchClient_Call) Run(run func(targetSession string)) *MockTmux_SwitchClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTmux_SwitchClient_Call) Return(_a0 string, _a1 error) *MockTmux_SwitchClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_SwitchClient_Call) RunAndReturn(run func(string) (string, error)) *MockTmux_SwitchClient_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchOrAttach provides a mock function with given fields: name, opts
func (_m *MockTmux) SwitchOrAttach(name string, opts model.ConnectOpts) (string, error) {
	ret := _m.Called(name, opts)

	if len(ret) == 0 {
		panic("no return value specified for SwitchOrAttach")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, model.ConnectOpts) (string, error)); ok {
		return rf(name, opts)
	}
	if rf, ok := ret.Get(0).(func(string, model.ConnectOpts) string); ok {
		r0 = rf(name, opts)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, model.ConnectOpts) error); ok {
		r1 = rf(name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTmux_SwitchOrAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchOrAttach'
type MockTmux_SwitchOrAttach_Call struct {
	*mock.Call
}

// SwitchOrAttach is a helper method to define mock.On call
//   - name string
//   - opts model.ConnectOpts
func (_e *MockTmux_Expecter) SwitchOrAttach(name interface{}, opts interface{}) *MockTmux_SwitchOrAttach_Call {
	return &MockTmux_SwitchOrAttach_Call{Call: _e.mock.On("SwitchOrAttach", name, opts)}
}

func (_c *MockTmux_SwitchOrAttach_Call) Run(run func(name string, opts model.ConnectOpts)) *MockTmux_SwitchOrAttach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.ConnectOpts))
	})
	return _c
}

func (_c *MockTmux_SwitchOrAttach_Call) Return(_a0 string, _a1 error) *MockTmux_SwitchOrAttach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTmux_SwitchOrAttach_Call) RunAndReturn(run func(string, model.ConnectOpts) (string, error)) *MockTmux_SwitchOrAttach_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTmux creates a new instance of MockTmux. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTmux(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTmux {
	mock := &MockTmux{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
